[package]
name = "ultra-rs"
version = "0.1.0"
authors = ["Lukas Krickl <lukas@krickl.dev>"]

[lib]
name = "ultrars"
path = "src/lib.rs"


[dependencies]
embedgdb={git="https://github.com/unlink2/embedgdb"}
